const fs = require('fs');
const path = require('path');
const assert = require('assert');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const workflowPath = path.join(root, '.github', 'workflows', 'update-scan-snapshot.yml');
const generatorPath = path.join(root, 'scripts', 'generate-scan-snapshot.py');
const validatorPath = path.join(root, 'scripts', 'validate-scan-snapshot.py');

assert.match(html, /const SCAN_LOGIC_VERSION\s*=/, '缺少掃描策略版本，無法拒絕舊邏輯快照');
assert.match(html, /const SCAN_SNAPSHOT_URL\s*=/, '缺少背景掃描快照網址');
assert.match(html, /function validateScanSnapshot\s*\(/, '缺少快照完整性與時效驗證');
assert.match(html, /generatedAt/, '快照驗證未檢查產生時間');
assert.match(html, /complete\s*!==\s*true|!snapshot\.complete/, '快照驗證未拒絕未完成掃描');
assert.match(html, /logicVersion\s*!==\s*SCAN_LOGIC_VERSION/, '快照驗證未拒絕不同策略版本');
assert.match(html, /SCAN_SNAPSHOT_MAX_AGE_MS\s*=\s*30\s*\*\s*60\s*\*\s*1000/, '快照有效期限必須限制為 30 分鐘');
assert.match(html, /snapshot-generator/, '背景產生器必須能略過快照，避免循環讀取舊結果');
assert.match(html, /_snapshotActive/, '缺少快照模式狀態');
assert.match(html, /_universeSourceOk/, '缺少動態幣池來源狀態');
assert.match(html, /IND_SYMS\.filter\(sym=>availableSymbols\.has\(sym\)\)/, '固定主流幣未用 OKX 可交易商品集合過濾');
assert.match(html, /_vegasScanCoverage/, '缺少逐幣掃描 coverage');
assert.match(html, /universeSourceOk/, '快照未驗證幣池來源成功');
assert.match(html, /coverage\.failed/, '快照未拒絕核心掃描失敗');
assert.match(html, /await r\.text\(\)/, '快照必須保留原始文字供跨語言 SHA-256 驗證');
assert.match(html, /snapshotTextWithoutContentHash/, '快照未以移除 hash 欄位後的原始文字驗證');
assert.match(html, /_provenance/, '快照結果缺少逐筆資料來源');
assert.match(html, /v\?\._provenance\?\.source!==['"]live['"]\|\|v\?\._provenance\?\.complete!==true/, '執行閘門必須逐筆拒絕非 live 或未完整資料');
assert.match(html, /if\s*\([^\n]*_snapshotActive[^\n]*\)\s*return false/, '快照模式不得通過可執行閘門');
assert.match(html, /快照觀察/, '快照結果必須清楚標示只能觀察');
assert.match(html, /loadScanSnapshot\s*\(\)/, '冷啟動沒有立即載入背景快照');
assert.match(html, /document\.addEventListener\(['"]DOMContentLoaded['"],async\s*\(\)=>[\s\S]{0,500}await loadScanSnapshot\(\)/, '必須先完成快照載入判定再啟動 live，避免競態');
assert.match(html, /function renderObservationRecs\s*\(/, 'Top5 缺少獨立的純快照觀察 renderer');
assert.match(html, /function renderRecs\([\s\S]{0,650}isObservationOnly[\s\S]{0,220}renderObservationRecs/, 'Top5 必須在任何 observation-only 資料出現時提前走純觀察 renderer');
assert.match(html, /純歷史觀察，不構成交易建議/, 'Top5 快照標題必須明示不是交易建議');
assert.match(html, /function openMOVEDetail\([\s\S]{0,260}isObservationOnly/, 'MOVE 共用詳情入口未阻擋快照／未完整 live');
assert.match(html, /function renderHotMovers\([\s\S]{0,2200}isObservationOnly/, '異動榜未逐筆降級成觀察');
assert.match(html, /function renderVolSpike\([\s\S]{0,3200}isObservationOnly/, '成交量訊號未逐筆降級成觀察');
assert.match(html, /function getOIVegasTag\([\s\S]{0,500}isObservationOnly/, 'OI+VEGAS 標籤未逐筆降級成觀察');
assert.match(html, /function openSectorDetail\([\s\S]{0,2600}isObservationOnly/, '板塊 modal 未逐筆降級成觀察');
assert.match(html, /function renderVolRank\([\s\S]{0,1800}isObservationOnly/, '成交量排行未逐筆降級成觀察');
assert.match(html, /function renderNewsFromMarket\([\s\S]{0,1800}!isObservationOnly/, '市場快訊仍可能把快照轉成做多／做空訊號');
assert.match(html, /function isObservationOnly\s*\(/, '缺少全站共用的快照觀察 helper');
assert.match(html, /function renderPullback\([\s\S]{0,260}isObservationOnly/, '回踩區未阻擋快照行動文案');
assert.match(html, /function renderNearPullback\([\s\S]{0,260}isObservationOnly/, '接近回踩區未阻擋快照行動文案');
assert.match(html, /function buildCtx\([\s\S]{0,1400}快照觀察[^\n]*不可.*進場/, 'AI context 未標示快照只能觀察');
assert.match(html, /_snapshotActive=false;_snapshotMeta=null;[\s\S]{0,180}renderVegas\(\)/, 'live 原子切換後必須重繪 VEGAS 與回踩 DOM');
assert.match(html, /const keepSnapshot=_snapshotActive&&vegasData\.length>0;[\s\S]{0,180}if\(!keepSnapshot\)[^\n]*vlist/, 'live 掃描開始時不得清掉有效快照 DOM');
assert.match(html, /const liveVegasData\s*=\s*\[\]/, '背景實掃必須與快照資料分離，避免一開始清空快照');
assert.doesNotMatch(html, /Math\.random\s*\(/, '禁止以假資料填補快照或訊號');

assert.ok(fs.existsSync(generatorPath), '缺少匿名瀏覽器快照產生器');
const generator = fs.readFileSync(generatorPath, 'utf8');
const validator = fs.readFileSync(validatorPath, 'utf8');
assert.match(generator, /page_errors/, '產生器必須蒐集並拒絕 JavaScript 錯誤');
assert.match(generator, /429/, '產生器必須檢查 API 限流');
assert.match(generator, /complete.*True/, '產生器輸出必須標示完整掃描');
assert.match(generator, /logicVersion/, '產生器輸出必須帶策略版本');
assert.match(generator, /scannedTotal/, '產生器輸出必須帶實際掃描總數');
assert.match(generator, /universeSourceOk/, '產生器必須拒絕動態幣池來源失敗');
assert.match(generator, /coverage/, '產生器必須保存逐幣 coverage');
assert.match(generator, /contentSha256/, '產生器必須保存內容 SHA-256');
assert.match(generator, /snapshot_text_without_content_hash/, '產生器未用原始快照文字計算 SHA-256');
assert.match(validator, /snapshot_text_without_content_hash/, '發布驗證器未用原始快照文字重算 SHA-256');
assert.match(validator, /parse_constant\s*=\s*reject_nonfinite/, '發布驗證器 JSON 解析必須拒絕 NaN／Infinity 常數');
assert.match(validator, /assert_all_finite\s*\(snapshot\)/, '發布驗證器必須遞迴拒絕所有欄位的非有限數字');
assert.match(generator, /allow_nan=False/, '產生器必須拒絕 NaN／Infinity JSON');
assert.match(generator, /math\.isfinite/, '產生器未拒絕非有限 score');
assert.match(validator, /math\.isfinite/, '發布驗證器未拒絕非有限 score');
assert.match(generator, /['"]bull['"][^\n]*['"]bear['"][^\n]*['"]neutral['"]/, '產生器未限制 signal allowlist');

assert.ok(fs.existsSync(workflowPath), '缺少定時背景掃描 workflow');
const workflow = fs.readFileSync(workflowPath, 'utf8');
assert.match(workflow, /cron:\s*['"]?\*\/15 \* \* \* \*['"]?/, '背景完整掃描必須每 15 分鐘排程');
assert.match(workflow, /workflow_dispatch:/, '背景掃描必須支援手動驗證');
assert.match(workflow, /permissions:[\s\S]*contents:\s*write/, 'workflow 缺少僅限內容寫入的權限宣告');
assert.match(workflow, /scan-cache/, '快照必須寫入獨立 scan-cache 分支');
assert.match(workflow, /generate-scan-snapshot\.py/, 'workflow 未執行正式快照產生器');
assert.match(workflow, /python -m http\.server 8789 --bind 127\.0\.0\.1/, 'workflow 必須從 checkout 的同一 commit 啟動本機站點');
assert.match(workflow, /http:\/\/127\.0\.0\.1:8789/, '產生器必須掃描本次 checkout，不得掃描可能延遲的 Pages');
assert.match(workflow, /github\.ref\s*==\s*['"]refs\/heads\/main['"]/, '發布必須限制 main 分支 commit');
assert.doesNotMatch(workflow, /s6432891-star\.github\.io\/lucky-star-signal/, 'workflow 不得把公開 Pages 冒充 GITHUB_SHA 版本');

console.log('✅ scan_snapshot_static.test.js passed');
